# Site
repository: Pavlo-Andrianatos/modern-resume-theme
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Constantinos Pavlo Andrianatos
title: BSc Computer Science Student
email: u17173389@tuks.co.za

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: Pavlo-Andrianatos
linkedin_username: pavlo-a-8b4b49112

# About Section
#about_title: About Me (Use this to override about section title)
about_profile_image: assets/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am a final year Computer Science student studying at the University of Pretoria. I have an interest in technology and science, I am
  eager to learn new technologies and acquire new skills to tackle new and intersting problems.

# Education Section
education_title: Education #(Use this to override about education section title)

# Experience Section
experience_title: Experience #(Use this to override about experience section title)

# Projects Section
projects_title: Competitions #(Use this to override about projects section title)

# More Section
more_title: Interests #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
 * Gaming
 * Astronomy
 * History
 * Computer Security

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: Pavlo-Andrianatos/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
